import { useState, type FormEvent } from "react";
import { bridgeAdministrationError, createBridge, type BridgeAdminSummary } from "../api/bridgeAdministrationApi";
import { backendBaseUrl } from "../config";

export function CreateBridgeDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (bridge: BridgeAdminSummary) => void }) {
  const [name, setName] = useState(""); const [routeNumber, setRouteNumber] = useState(""); const [routeName, setRouteName] = useState(""); const [region, setRegion] = useState(""); const [station, setStation] = useState(""); const [status, setStatus] = useState("在用"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; setBusy(true); setError(null); try { onCreated(await createBridge(backendBaseUrl, { bridge_name: name.trim(), route_number: routeNumber, route_name: routeName, administrative_region: region, station_mark: station, status })); } catch (caught) { setError(bridgeAdministrationError(caught)); } finally { setBusy(false); } }
  return <div className="dialog-backdrop" role="presentation"><form className="workspace-dialog create-bridge-dialog" role="dialog" aria-modal="true" aria-labelledby="create-bridge-title" onSubmit={(event) => void submit(event)}><h2 id="create-bridge-title">添加桥梁</h2><label>桥梁名称<input required maxLength={200} value={name} onChange={(e) => setName(e.target.value)} /></label><div className="bridge-form-grid"><label>路线编号<input maxLength={100} value={routeNumber} onChange={(e) => setRouteNumber(e.target.value)} /></label><label>路线名称<input maxLength={200} value={routeName} onChange={(e) => setRouteName(e.target.value)} /></label><label>行政区划<input maxLength={200} value={region} onChange={(e) => setRegion(e.target.value)} /></label><label>桩号<input maxLength={100} value={station} onChange={(e) => setStation(e.target.value)} /></label><label>状态<select value={status} onChange={(e) => setStatus(e.target.value)}><option>在用</option><option>停用</option><option>拆除</option></select></label></div>{error ? <p className="error-text" role="alert">{error}</p> : null}<div className="dialog-actions"><button type="button" disabled={busy} onClick={onClose}>取消</button><button type="submit" disabled={busy || !name.trim()}>{busy ? "正在添加…" : "添加桥梁"}</button></div></form></div>;
}
