import { useEffect, useState } from "react";
import { bridgeAdministrationError, deleteBridges, fetchBridgeDeletionImpact, type BridgeDeletionPreview, type DeleteBridgesResult } from "../api/bridgeAdministrationApi";
import { backendBaseUrl } from "../config";

export function DeleteBridgesDialog({ bridgeIds, onClose, onSelectionChanged, onCompleted }: { bridgeIds: string[]; onClose: () => void; onSelectionChanged: () => void; onCompleted: (result: DeleteBridgesResult) => void }) {
  const [preview, setPreview] = useState<BridgeDeletionPreview | null>(null); const [reason, setReason] = useState(""); const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<DeleteBridgesResult | null>(null);
  useEffect(() => { fetchBridgeDeletionImpact(backendBaseUrl, bridgeIds).then(setPreview).catch((caught) => { setError(bridgeAdministrationError(caught)); if ((caught as { code?: string }).code === "bridge_selection_changed") onSelectionChanged(); }); }, [bridgeIds, onSelectionChanged]);
  async function submit() { if (!preview) return; setBusy(true); setError(null); try { const value = await deleteBridges(backendBaseUrl, { reason: reason.trim(), confirmation_text: confirmation, items: preview.bridges.map((item) => ({ bridge_id: item.bridge.id, impact_token: item.impact_token })) }); setResult(value); onCompleted(value); } catch (caught) { setError(bridgeAdministrationError(caught)); } finally { setBusy(false); } }
  const canDelete = Boolean(preview && reason.trim() && confirmation === preview.confirmation_text && !busy);
  return <div className="dialog-backdrop" role="presentation"><section className="workspace-dialog delete-bridges-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-bridges-title"><h2 id="delete-bridges-title">永久删除桥梁档案</h2>{!preview && !error ? <p>正在核对删除影响…</p> : null}{preview && !result ? <><div className="danger-callout"><strong>此操作不可撤销</strong><p>将逐座永久删除所选桥梁的全部年度、导入、病害、评分和独占归档文件。</p></div>{preview.bridges.map((item) => <article className="bridge-delete-impact" key={item.bridge.id}><h3>{item.bridge.system_number}　{item.bridge.bridge_name}</h3><p>年度 {item.counts.inspection_years} · 版本 {item.counts.inspection_versions} · 导入 {item.counts.import_records} · 构件 {item.counts.bridge_components} · 病害 {item.counts.defect_observations} · 文件 {item.counts.archived_files_to_delete}</p>{item.active_edit_locks.map((lock) => <p className="lock-warning" key={lock.import_record_id}>{lock.owner_display_name} 正在编辑，本次不能删除</p>)}</article>)}<label>删除原因<textarea maxLength={4000} value={reason} onChange={(e) => setReason(e.target.value)} /></label><label>请输入“{preview.confirmation_text}”确认<input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /></label></> : null}{result ? <div><h3>已处理</h3>{result.results.map((item) => <p key={item.bridge_id}>{item.status === "deleted" ? "✓" : "✗"} {item.system_number} {item.bridge_name}：{item.status === "deleted" && item.file_cleanup_status === "pending" ? `业务档案已完整删除；${item.pending_file_count} 个孤立归档文件等待后台清理` : item.status === "deleted" ? "已删除" : item.message}</p>)}</div> : null}{error ? <p className="error-text" role="alert">{error}</p> : null}<div className="dialog-actions"><button type="button" disabled={busy} onClick={onClose}>{result ? "关闭" : "取消"}</button>{!result ? <button className="danger-button" type="button" disabled={!canDelete} onClick={() => void submit()}>{busy ? "正在删除…" : "永久删除"}</button> : null}</div></section></div>;
}
